return {
    "Sosuke (Storm)",
    "Noruto (Six Tails)",
    "Igros (Elite Knight)",
    "Obita (Awakened)",
    "Haruka Rin (Dancer)",
    "Song Jinwu (Monarch)",
    "Cha-In (Blade Dancer)",
    "Alocard (Vampire King)",
    "Vogita Super (Awakened)",
    "Itochi",
    "Roku (Dark)",
    "Goi",
    "Kinaru",
    "Grim Wow",
    "Agony",
    "Alocard",
    "Sosuke (Hebi)",
    "Vogita Super",
    "UNUSED",
    "Noruto (Sage)",
    "Song Jinwu",
    "Cha-In",
    "Igros",
    "Obita",
    "Haruka Rin",
    "Kokashi",
    "Genitsu",
    "Genas",
    "Inosake",
    "Gaari",
    "Kinnua",
    "Alligator",
    "Shinzi",
    "Pickleo",
    "Sprintwagon",
    "Ichiga",
    "Joe",
    "Jon",
    "Luffo",
    "Noruto",
    "Roku",
    "Rukio",
    "Sanjo",
    "Sosuke",
    "Vogita",
    "Blossom",
    "Takaroda",
    "UNUSED",
    "Bean",
    "Akazo",
    "Renguko",
    "Tengon",
    "Akazo (Destructive)",
    "Tengon (Flashiness)",
    "Renguko (Purgatory)",
    "Todu",
    "Nazuka",
    "Inamuki",
    "Nobaba",
    "Chaso",
    "UNUSED",
    "Gujo",
    "Jag-o",
    "UNUSED",
    "Tuji",
    "Itaduri",
    "Broly",
    "Julias",
    "Zion",
    "Legendary Super Brolzi",
    "Mechamar",
    "Mohato",
    "Sukono",
    "Tuji (Sorcerer Killer)",
    "Chaso (Blood Curse)",
    "UNUSED",
    "Jag-o (Volcanic)",
    "UNUSED",
    "Todu (Unleashed)",
    "Gujo (Infinity)",
    "Julias (Eisplosion)",
    "Zion (Burdelyon)",
    "Okorun",
    "Okorun (Turbo)",
    "Saiko",
    "Saiko (Spirit Medium)",
    "Mimi",
    "Mimi (Psychic)",
    "Pweeny",
    "Pweeny (Boxer)",
    "Divalo (Requiem)",
    "Johnni",
    "Johnni (Infinite Spin)",
    "Giro",
    "Giro (Ball Breaker)",
    "Diogo",
    "Diogo (Alternate)",
    "Valentine",
    "Valentine (Love Train)",
    "Valentine (AU)",
    "Ishtar",
    "Ishtar (Divinity)",
    "Cu Chulainn",
    "Cu Chulainn (Child of Light)",
    "Gilgamesh",
    "Gilgamesh (King of Heroes)",
    "Saber",
    "Saber (King of Knights)",
    "Saber (Alter)",
    "Saber (Black Tyrant)",
    "Medusa",
    "Medusa (Gorgon)",
    "Medea",
    "Medea (Witch of Betrayal)",
    "Archer",
    "Archer (Counter Spirit)",
    "Saber (Alternate)",
    "Seban",
    "Dodara",
    "Dodara (Explosive)",
    "Sosora",
    "Sosora (Puppeteer)",
    "Emmie",
    "Emmie (Ice Witch)",
    "Foboko",
    "Foboko (Hellish)",
    "Karem",
    "Karem (Chilled)",
    "Rom and Ran",
    "Rom and Ran (Fanatic)",
    "Regnaw",
    "Regnaw (Rage)",
    "Rodock",
    "Giyu",
    "Rogita (Super 4)",
    "Rogita (Super 4) (Clone)",
    "Soburo",
    "Soburo (Contract)",
    "Sokora",
    "Sokora (Angra Mainyu)",
    "Lilia",
    "Lilia and Berserker",
    "Saber (Black Tyrant)",
    "Isdead",
    "Isdead (Romantic)",
    "Saber (A.W.E.)",
    "Caster",
    "Eizan",
    "Eizan (Aura)",
    "Gazelle",
    "Gazelle (Zombie)",
    "Ichiga (True Release)",
    "Ichiga (Savior)",
    "Kempache",
    "Kempache (Feral)",
    "Kiskae",
    "Kiskae (Scientist)",
    "Orehimi",
    "Orehimi (Faith)",
    "Oryo",
    "Oryo (Antithesis)",
    "Yuruicha",
    "Yuruicha (Raijin)",
    "Dave",
    "Dave (Cyber Psycho)",
    "Luce",
    "Luce (Hacker)",
    "Yehowach",
    "Yehowach (Almighty)",
    "Yomomata",
    "Yomomata (Captain)",
    "Bomberetta (Zombie)",
    "Totsero (Zombie)",
    "Friran",
    "Friran (Teacher)",
    "Choy Jong En",
    "Choy Jong En (Guild Leader)",
    "Song Jinwu and Igros",
    "Sabe",
    "Dawntay",
    "Lethal Bee",
    "Octopus",
    "Stone Lee",
    "Vigil",
    "Hercool",
    "Rohan (Adult)",
    "Roku (Angel)",
    "Boo",
    "Dawntay (Jackpot)",
    "Vigil (Power)",
    "Hercool and Mr Boo",
    "Ultimate Rohan",
    "Boo (Evil)",
    "Boockleo (Evil)",
    "Boohon (Evil)",
    "Bootonks (Evil)",
    "Kid Boo (Evil)",
    "Roku (Super 3)",
    "Super Boo (Evil)",
    "Super Vogito",
    "Vogita (Angel)",
    "LagShooter",
    "Vigil (Doppelganger)",
    "Clatakiri",
    "Clatakiri (Mochi)",
    "Deruta",
    "Deruta (Hunt)",
    "Delusional Boy",
    "Lord of Shadows",
    "Smith John",
    "Lfelt",
    "Lfelt (Love)",
    "Byeken",
    "Byeken (Ronin)",
    "Astolfo",
    "Astolfo (Rider of Black)",
    "Brisket",
    "Brisket (Yo-Yo)",
    "Gear Boy",
    "Gear Boy (Hungry)",
    "Kazzy",
    "Kazzy (Queen)",
    "NotGoodGuy",
    "NotGoodGuy (Free)",
    "Al",
    "Al (Good)",
    "Dark Mage",
    "Dark Mage (Evil)",
    "Arc",
    "Hebano",
    "Marlin",
    "Rudie",
    "Conqueror vs Invulnerable",
    "Slime",
    "Koguro (Unsealed)",
    "Arc (True Ancestor)",
    "Hebano (Clematis)",
    "Marlin (Gluttony)",
    "Rudie (Prodigy)",
    "Slime (King)",
    "Ackers",
    "Reimu",
    "Sakuya",
    "Aurin",
    "Riner",
    "Zak",
    "Arin",
    "Giant Queen",
    "Reimu (Shrine Maid)",
    "Sakuya (Time Maid)",
    "Ackers (Ken)",
    "Ackers (Levy)",
    "Ackers (Makoso)",
    "Aurin (Nuclear Giant)",
    "Riner (Reinforced Giant)",
    "Zak (Ape Giant)",
    "Arin (Rumbling)",
    "Giant Queen (Founder)",
    "First Giant",
    "Leo",
    "Leo (Fangs)",
    "Ali",
    "Ali (Djinn)",
    "Hei",
    "Hei (Black Dragon)",
    "Newsman",
    "Newsman (Forecast)",
    "Quetzalcoatl",
    "Quetzalcoatl (Sun God)",
    "Iscanur (Pride)",
    "Monkey King (Awakened)",
    "Monkey King (Clone)",
    "The Falcon",
    "The Falcon (Sacrifice)",
    "The Falcon (of Darkness)",
    "The Falcon (of Light)",
    "The Smith",
    "The Smith (Forged)",
    "The Struggler",
    "The Struggler (Rampage)",
    "The King",
    "The King (Apostle)",
    "The Witch",
    "The Witch (Disciple)",
    "GG",
    "GG (Possessed)",
    "Goblin Killer",
    "Goblin Killer (Trapper)",
    "Priestess",
    "Priestess (Holy)",
    "Lord Friezo",
    "Lord Friezo (Emperor)",
    "Alien Cadet",
    "Alien Soldier",
    "Alien Elite",
    "Rogita",
    "Rogita (Super)",
    "Brolzi Super (Wrathful)",
    "Wolf (Resurrection)"
}